"""Report : serialise les findings triangules en markdown backlog.

Format de sortie strict :

    # AUDIT HERMES — YYYY-MM-DD HH:MM UTC

    ## Summary
    - DEAD       : N (3/3 lenses)  — candidats suppression haute confiance
    - CANDIDATE  : N (2/3 lenses)
    - WATCH      : N (1/3 lenses)
    - excluded   : N (doctrine exclusions)

    ## DEAD (3/3) — haute confiance
    ### `<name>` [kind]
      - statique : <citation>
      - runtime  : <citation>
      - decision : <citation>
      → candidat suppression. Verdict : toi.

Fichier ecrit sous docs/AUDIT_HERMES_YYYY-MM-DD.md. Append-only convention
(si le fichier existe deja, suffix _hh-mm).

ZERO ECRITURE en dehors de docs/. Aucune modification de code, jamais.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any


def serialize(audit: dict[str, Any], out_dir: Path = Path("docs")) -> Path:
    """Serialise audit dict (de runner.run()) en markdown."""
    now = datetime.utcnow()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M")
    fname = f"AUDIT_HERMES_{date_str}.md"
    out_path = out_dir / fname
    if out_path.exists():
        # Append time suffix to avoid overwrite
        fname = f"AUDIT_HERMES_{date_str}_{now.strftime('%H-%M')}.md"
        out_path = out_dir / fname

    lines: list[str] = []
    summary = audit.get("summary", {})
    meta = audit.get("meta", {})
    lines.append(f"# AUDIT HERMES — {date_str} {time_str} UTC")
    lines.append("")
    lines.append(f"**Window** : {meta.get('window_days', 90)}d &middot; "
                 f"**Targets** : {', '.join(meta.get('targets', []))} &middot; "
                 f"**Vulture min-confidence** : {meta.get('vulture_min_confidence', 80)}%")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **DEAD**       : {summary.get('DEAD', 0)} (3/3 lenses) — candidats suppression haute confiance")
    lines.append(f"- **CANDIDATE**  : {summary.get('CANDIDATE', 0)} (2/3 lenses)")
    lines.append(f"- **WATCH**      : {summary.get('WATCH', 0)} (1/3 lenses)")
    lines.append(f"- **excluded**   : {summary.get('excluded', 0)} (doctrine exclusions, voir bas)")
    lines.append(f"- **total findings** : {summary.get('total_findings', 0)}")
    lines.append("")

    triangulated = audit.get("triangulated", [])

    def emit_section(_label: str, n_lenses: int) -> None:
        section_items = [f for f in triangulated
                         if f.n_lenses == n_lenses and not f.excluded]
        if not section_items:
            return
        title = {3: "DEAD (3/3) — haute confiance",
                 2: "CANDIDATE (2/3) — confiance moyenne",
                 1: "WATCH (1/3) — a regarder"}[n_lenses]
        lines.append(f"## {title}")
        lines.append("")
        for f in section_items:
            lines.append(f"### `{f.name}`")
            lines.append("")
            for lens, ev in f.evidence.items():
                lines.append(f"  - **{lens}** : {ev}")
            verdict_line = "  → candidat suppression. **Verdict : toi.**" if n_lenses == 3 \
                else f"  → a regarder ({n_lenses}/3 lenses). Verdict : toi."
            lines.append(verdict_line)
            lines.append("")

    emit_section("DEAD", 3)
    emit_section("CANDIDATE", 2)
    emit_section("WATCH", 1)

    # Doctrine exclusions
    excluded_items = [f for f in triangulated if f.excluded]
    if excluded_items:
        lines.append("## Excluded (doctrine)")
        lines.append("")
        lines.append("*Items match une regle doctrine -- ne sont PAS proposes en supression.*")
        lines.append("")
        for f in excluded_items:
            lines.append(f"- `{f.name}` ({f.n_lenses}/3) — {f.exclusion_reason}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("**Generated by hermes.inspector v0.1.0** — Tier R read-only, audit doctrine SAS.")
    lines.append("Aucune affirmation 'mort' n'est un verdict ; chacune est un candidat pour ton jugement.")
    lines.append("")
    lines.append("Pour relancer : `python -m hermes.inspector --since 90d`")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path
